# Generated by Django 3.2.16 on 2023-01-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование ')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание ')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='VersionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions_reference', to='medicine.reference')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочника',
            },
        ),
        migrations.CreateModel(
            name='ElementReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=100, verbose_name='Значение элемента')),
                ('version_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_reference', to='medicine.versionreference')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
    ]
